### PR TITLE
KEYCLOAK-6161: Unignore tests and fix formatting

### PR DESCRIPTION
**Pull request by foo4u**
Fix formatting issues in unignored specs.

### CODE REVIEW

**Comment by foo4u** [comment]
I'll rebase after #106 is merged.

**Comment by abstractj** [comment]
I'm rebasing it and will merge on master.

**Comment by abstractj** [comment]
@foo4u I was trying to save you some time and rebase myself. But with protected branches, now I no longer can merge my own branch. Please rebase and change the title to reflect the original Jira, just like this https://github.com/abstractj/keycloak-nodejs-connect/commit/4b3b6b18f1cc98b7908e4e8f95805d1c001856a3

**Comment by abstractj** [comment]
Rebased here https://github.com/keycloak/keycloak-nodejs-connect/pull/109

**Comment by foo4u** [comment]
Thanks, just sat down to do it myself and saw it on master.

**Comment by abstractj** [comment]
@foo4u no problem Scott. Thanks for your PR.

**Pull request closed without merging**
