### PR TITLE
[KEYCLOAK-4162] Multi-tenancy support

### PR DESCRIPTION
**Pull request by jderuere**
- Enable to pass an array of config, one per realm
- When using multiple configs, a resolver that fetch the realm name from the request needs to be provide
- Retrocompatible, it still works as usual

### CODE REVIEW

**Comment by jardakotesovec** [comment]
Hi, it would be awesome to have this feature baked in so no need for [alternative packages](https://github.com/devsu/keycloak-nodejs-multirealm), is something blocking it?

**Comment by jardakotesovec** [comment]
Please let me know if there is something I can help with to make this PR happen :-).

**Comment by paulmowat** [comment]
Would be great to have this feature. Ideal for a new project I'm just about to start.

**Comment by jardakotesovec** [comment]
@paulmowat Hi, I shared my approach to handle multiple realms with existing keycloak-connect with simple wrapper in [jira](https://issues.jboss.org/browse/KEYCLOAK-4162). So far I think its good solution, but we are also in initial stage of the project, so time will tell if there are some issues with this approach.

**Comment by comply-online** [comment]
any news about this? It would be a great addition

**Comment by abstractj** [comment]
@jderuere thanks for putting this together and sorry if I didn't get back to you earlier. We are approaching code freeze and have been prioritizing bugs, instead of new features. For now I'm putting this change on "hold". Even thoughthis change is a great addition to the Node.js adapter, it also requires more testing, just to make sure that everything is in place.

**Comment by abstractj** [comment]
@jderuere thanks for submitting this. It's been a while since we talked and this PR definitely need some upgrade. Even though I believe this would be something interesting for the adapter, this is a feature that introduces considerable changes, for that, we really need integration tests instead of unit tests, plus, update the documentation.

For now I'm closing this, but if you would like to add the integration tests and docs, please reopen this pull-request. Otherwise, in the future we gonna take into consideration your changes and give the proper credits.

@jardakotesovec @paulmowat @comply-online I appreciate your interest in this change, but in order to keep quality, we need to provide integration tests and documentation. If some of you are interested on it, feel free to work together with @jderuere.

**Comment by jardakotesovec** [comment]
@abstractj No problem, the approach I illustrated in [jira](https://issues.jboss.org/browse/KEYCLOAK-4162) works just fine for us.. so I don't think there is real need to support that inside the middleware itself.

**Pull request closed without merging**
