### PR TITLE
Proxy feature

### PR DESCRIPTION
**Pull request by vichak**
Hello,
I push again this PR => https://github.com/keycloak/keycloak-nodejs-connect/pull/111

### CODE REVIEW

**Comment by dynamic11** [comment]
This feature would be very helpful!

**Comment by ianwilk20** [comment]
> This feature would be very helpful!

Agreed! @vichak do you have an update on this?

**Comment by debovema** [comment]
:eyes:

**Comment by abstractj** [comment]
Please, before creating a new PR make sure you follow the [contributing guidelines](https://github.com/keycloak/keycloak-nodejs-connect/blob/c3018fae6f5cae8aaf7af8c04116fc900b28d969/CONTRIBUTING.md). As already explained in #111, here are some missing items in your pull request:

- Lack of tests
- Lack of a proper discussion on the dev mailing list
- Lack of authorship, you got the changes from the previous author, but I don't see any mention to his work
- Also, please refer to the Jira in your commit message

For now I'm closing this, but if you find some time to review our guidelines, please open a new PR.

**Pull request closed without merging**
