### PR TITLE
KEYCLOAK-5771

### PR DESCRIPTION
**Pull request by beau6183**
Introduces the option to return a promise from `keycloak.protect` in order to facilitate async operations in the middleware.

### CODE REVIEW

**Comment by stianst** [comment]
Thanks for the contribution. There are some tests failing here so seems like there's some regressions introduced.

We are currently in feature freeze for Keycloak 3.x and won't be able to merge this until we start development on Keycloak 4.x.

**Comment by beau6183** [comment]
I'll get it fixed up this weekend. Thanks!

**Comment by abstractj** [comment]
@beau6183 please rebase your changes against master and squash your commits into a single commit.

**Comment by stianst** [comment]
@beau6183 please rebase and squash

**Comment by keycloak-testing** [comment]
@beau6183 closing it. Please, feel free to reopen if you still plan to work on it.

**Comment by abstractj** [comment]
@beau6183 closing it. Please reopen the PR if you still want to work on it.

**Pull request closed without merging**
