### PR TITLE
Minor fixes and updates

### PR DESCRIPTION
**Pull request by helio-frota**
* Some jshint fixes
* Dependencies updated
* Grunt-mrdoc commented due instability of the plugin.

### CODE REVIEW

**Comment by lholmquist** [comment]
looks good.  

perhaps we should be adding in a .jshintrc file with the specified jshint rules?  that could be another pr too

**Comment by helio-frota** [comment]
@lholmquist I agree.
@lance other day commented on the establishment of rules.

**Comment by abstractj** [comment]
@lholmquist @helio-frota +1 and makes sense for another PR

@helio-frota regarding the mr-doc commented. Why not just remove it?

**Comment by helio-frota** [comment]
@abstractj for me is ok, we can think later about the docs.

**Pull request closed without merging**
