### PR TITLE
Update example to version 0.2.1

### PR DESCRIPTION
**Pull request by foo4u**
Example version still infinitely redirects. Update example to 0.2.1.

### CODE REVIEW

**Comment by foo4u** [comment]
Alternatively what if we set the example to refer to the parent directory for Keycloak Connect:

```
"keycloak-connect": "file:../",
```

**Comment by abstractj** [comment]
@foo4u +1 to the second alternative. @lance @lholmquist what do you think?

**Comment by helio-frota** [comment]
@foo4u good, this solves the problem with keep updating the example
+1
also better to update the doc about `npm link`.

**Comment by foo4u** [comment]
Ok, will update the PR.

**Comment by foo4u** [comment]
Going to close this as I see a commit in master that uses the parent folder as the source for Keycloak Connect.

**Pull request closed without merging**
