### PR TITLE
KEYCLOAK-11885 Add keycloak.d.ts to "files" property

### PR DESCRIPTION
**Pull request by wederer**
Without this the keycloak.d.ts is not included in the packaged tarball.

### CODE REVIEW

**Comment by abstractj** [comment]
Travis failures were fixed and merged here https://github.com/keycloak/keycloak-nodejs-connect/pull/223

**Comment by abstractj** [comment]
@wederer could you please rebase? In this way we can make sure that Travis is happy.

**Comment by wederer** [comment]
@abstractj I hope I did this correctly ;)

**Comment by abstractj** [comment]
@wederer of course, thank you. I will just wait to hear from @ASzc, because I'm not sure if we need the changes for https://github.com/keycloak/keycloak-nodejs-connect/blob/master/product/pom.xml#L62

**Comment by ASzc** [comment]
Tried it locally, and yes, you'll need:

```diff
diff --git a/product/pom.xml b/product/pom.xml
index 3056843..c0979c8 100644
--- a/product/pom.xml
+++ b/product/pom.xml
@@ -69,6 +69,7 @@
                                         <include>stores/**</include>
                                         <include>test/**</include>
                                         <include>uuid.js</include>
+                                        <include>keycloak.d.ts</include>
                                     </includes>
                                 </resource>
                             </resources>
```

for the file to be available to the product build

**Comment by abstractj** [comment]
Thanks @ASzc. @wederer could you please included the changes at the POM file as Alex suggested?

**Comment by abstractj** [comment]
@wederer your PR looks good, but we need to introduce the changes that @ASzc mentioned. Would you like to move forward with this change?

**Comment by wederer** [comment]
@abstractj Sorry for the delay. I added the commit.
Offtopic: I keep getting knocked off the keycloak-dev mailing list (Your membership in the mailing list keycloak-dev has been disabled due to excessive bounces). Is there another way to communicate with the keycloak devs?

**Comment by abstractj** [comment]
> @abstractj Sorry for the delay. I added the commit.
> Offtopic: I keep getting knocked off the keycloak-dev mailing list (Your membership in the mailing list keycloak-dev has been disabled due to excessive bounces). Is there another way to communicate with the keycloak devs?

Apologies for being really boring, but could you please fix the formatting https://github.com/keycloak/keycloak-nodejs-connect/blob/4b6924ca35eb45bb6c257744180d16983c5c5e4a/product/pom.xml#L72 ?

Regards the mailing list, we've been discussing the fix for it. The same happens to me, but temporarily for now, you have to activate again your membership.

**Comment by wederer** [comment]
@abstractj Of course.

**Pull request merged**
