### PR TITLE
KEYCLOAK 7087 - Crashes due to missing sanity checks on admin URLs

### PR DESCRIPTION
**Pull request by gkdr**
Fix for problem reported at https://issues.jboss.org/browse/KEYCLOAK-7087
...and a bit extra

### Checklist

- [ ]  Squash the commits into one

- [ ] Add integration tests to reproduce the issue

### CODE REVIEW

**Comment by abstractj** [comment]
@gkdr would you like to move forward with this PR?

**Comment by gkdr** [comment]
@abstractj I looked a bit into your testing setup but I don't think I can reserve the time to write the tests you require, so I'd like to take you up on your offer to look at it yourself :D
I assumed you'd just squash the commits after you added yours, but I can still do it if it makes it easier for you somehow.

**Comment by abstractj** [comment]
@gkdr I appreciate you took the time submitting this change, but at the moment neither me or anyone in the team have extra bandwidth to write the integration tests for your PR. Would you like to move forward with this change and write the tests? Otherwise, I'm afraid we will need to close this until someone find the time to work on it.

**Comment by gkdr** [comment]
As it does not seem to be a hurry I will probably be able to make some time for it.

**Comment by abstractj** [comment]
@gkdr I'm closing this PR for now. Feel free to open a new one when you're ready to submit the changes.

Thank you

**Pull request closed without merging**
