### PR TITLE
Proxy feature

### PR DESCRIPTION
**Pull request by gigaga**
It will be great if we could use keycloak-connect behind proxy.
Currently, http / https modules used to request to Keycloak server don't implement a proxy use.

https://issues.jboss.org/browse/KEYCLOAK-6441

### CODE REVIEW

**Comment by abstractj** [comment]
@gigaga please rebase your changes against master and squash your commits in a single commit. Also, please notice that the build is broken, so it has to be fixed.

Thank you in advance.

**Comment by gigaga** [comment]
@abstractj Done :)

**Comment by abstractj** [comment]
@gigaga Thanks so much for spending time on this amazing patch. I really appreciate it. However there are some requirements we have to tick before any merge:

- [ ] Like I mentioned, please squash your commits in a single one. This makes our review process better.

- [ ] Please document the feature. Otherwise people will never understand how to use the great you've done. Send the pull-request to https://github.com/keycloak/keycloak-documentation/blob/911336913b959e7d728b5c198b102b2ca239c70c/securing_apps/topics/oidc/nodejs-adapter.adoc

- [ ] Rebase your changes against master

Please let me know if still would like to move forward with this.

**Comment by abstractj** [comment]
@gigaga thank you for putting this together. Do you have any idea how we could write a good integration test for it? Maybe spin up nginx on Travis?

**Comment by gigaga** [comment]
@abstractj Putting this together? Sorry, I don't understand what you want.
Concerning test, effectively, I don't see how implement an efficient test :(

**Comment by gigaga** [comment]
Maybe by using node-http-proxy? That could be started automatically with tests (proxy startup code directly in tests files).
What do you think about that?

**Comment by abstractj** [comment]
> @abstractj Putting this together? Sorry, I don't understand what you want.
> Concerning test, effectively, I don't see how implement an efficient test :(

What I meant was: thanks for spending your time rebasing and writing the docs.

**Comment by abstractj** [comment]
> Maybe by using node-http-proxy? That could be started automatically with tests (proxy startup code directly in tests files).
> What do you think about that?

I think that would be really nice for testing. Would you like to look at this? That would be really appreciated if possible. Otherwise, I can add to my queue and look at this in some weeks.

**Comment by gigaga** [comment]
Ok, I'm going to try 😁

**Comment by abstractj** [comment]
@gigaga I'm closing it for now. But feel free to reopen when you get the new changes in. I will be more than happy to review.

**Pull request closed without merging**
