### PR TITLE
KEYCLOAK-9069 - Refactor using axios instead roi

### PR DESCRIPTION
**Pull request by helio-frota**

### CODE REVIEW

**Comment by abstractj** [comment]
@helio-frota overall looks good. Could you please change the commit message to something like KEYCLOAK-9069 - Refactor using axios instead roi? It will make easier for people to go through Jiras later. I already renamed that Jira.

**Comment by helio-frota** [comment]
@abstractj commit message changed. 
thanks!

**Comment by abstractj** [comment]
@helio-frota FYI PR was marked as "hold" only because we are in the middle of the release. But overall the code looks good to go in the next releases.

**Comment by helio-frota** [comment]
@abstractj Thank you for the extra information. :+1:

**Pull request merged**
