### PR TITLE
KEYCLOAK-10359 Run tests with chrome instead of phantomjs

### PR DESCRIPTION
**Pull request by mhajas**

### CODE REVIEW

**Comment by abstractj** [comment]
@mhajas ignore my comment, you fixed it already.

**Comment by mhajas** [comment]
@abstractj @vmuzikar The commit is ready to merge, it is working also in Jenkins.

**Comment by abstractj** [comment]
@mhajas Just wait a bit, please. I would like to have @vmuzikar's review.

**Comment by mhajas** [comment]
@vmuzikar Thanks for the review. This is a good idea. I updated PR now it is possible to do something like that:

````
node test/utils/webdriver.js --chromedriverPath=/home/mhajas/soft/chromedriver '--chromeArguments=--disable-infobars --start-fullscreen'
````

**Comment by vmuzikar** [comment]
@mhajas Thanks for the super quick update!

How is it supposed to work? :) When I try your suggested command:
```
node test/utils/webdriver.js '--chromeArguments=--disable-infobars --start-fullscreen'
```
it accepts (prints) the extra arguments but then just exists immediately (as expected).

Trying:
```
npm test '--chromeArguments=--disable-infobars --start-fullscreen'
```
doesn't seem to have any effect.

**Pull request merged**
