### PR TITLE
KEYCLOAK-5918

### PR DESCRIPTION
**Pull request by gigaga**
https://issues.jboss.org/browse/KEYCLOAK-5918

### CODE REVIEW

**Comment by stianst** [comment]
Thanks for the PR. We need to have tests added for this.

We can also not accept any more changes/enhancements for Keycloak 3.x as we are currently in feature freeze and won't be able to merge this until we start development on Keycloak 4.x

**Comment by gigaga** [comment]
@stianst OK, no problem!

**Comment by abstractj** [comment]
@gigaga FYI I just commented on Jira

**Comment by abstractj** [comment]
I appreciate you took your time to contribute with this change, but we don't think is a good idea to add it to the codebase. Instead, we created a new Jira https://issues.jboss.org/browse/KEYCLOAK-6173 to provide a dummy token for dev environments.

You're very welcome to comment on that and add whatever you think is missing.

Thank you.

**Pull request closed without merging**
