### PR TITLE
remove this and make the store function functional

### PR DESCRIPTION
**Pull request by lholmquist**
@lance @abstractj  @helio-frota mind taking a quick look.

For https://issues.jboss.org/browse/KEYCLOAK-3199

instead of adding the function keyword back in, i've made it more "functional" so its not as confusing where this comes from

### CODE REVIEW

**Comment by lance** [comment]
LGTM - any chance you could add a unit test of some kind?

**Comment by lholmquist** [comment]
@lance oh, right,  i was going to do that

**Comment by lholmquist** [comment]
@lance this is turning out to be a little tricky to test,  i'm going to probably merge this, and do a release so things are breaking anymore,  then go back and do the tests

**Comment by lance** [comment]
+1

**Pull request merged**
