### PR TITLE
[KEYCLOAK-4162] Multi-tenancy support

### PR DESCRIPTION
**Pull request by jderuere**
- Enable to pass an array of config, one per realm
- When using multiple configs, a resolver that fetch the realm name from the request needs to be provide
- Retrocompatible, it still works as usual

### CODE REVIEW

**Comment by gangapatnam-suresh** [comment]
Hi, I would like to have this feature support for one of my client application running on nodejs. Appreciate if any early release.
Thanks.

**Comment by abstractj** [comment]
@jderuere do you still want to work in this feature? If yes, please do the rebase.

**Comment by jderuere** [comment]
Hi. I'm currently in holidays. I'll work on it as soon as possible  (in a
week probably)

**Comment by abstractj** [comment]
@jderuere no problem, enjoy and have fun.

**Comment by jderuere** [comment]
Check #118

**Pull request closed without merging**
